### ISSUE TITLE
Question: Support for Thermostats

### ISSUE THREAD

**Issue by christopher-walker** [fabsrc/home-assistant-alexa-proxy#3]
Hi,

 Does this proxy support thermostats? I am currently using haaska which does. However I am looking to change my dns which would require some effort with haaska. I tested home-assistant-alexa-proxy last night and managed to discover some of my devices but the thermostats did not appear.

Thanks

Chris

**Comment by fabsrc** [comment]
Hi Chris,

yes, it should support thermostats as well. This code basically does the same thing as Haaska: proxying requests from Alexa to Home Assistant. There actually is no additional logic involved here.

If some of your devices are not discovered correctly, maybe try to discover them again or check your Home Assistant configuration.

I just checked my Alexa app and my thermostat is showing up there.

**Comment by christopher-walker** [comment]
Thanks for the reply.
 I will give it another go, I assume that home assistant is configured correctly as all is working in haaska, it just seems easier to change the environment variable than needing to recompile when changing my domain name.

Thanks again 👍

**Comment by christopher-walker** [comment]
Hi @fabsrc 
 Turns out the devices showing up were devices connected to the hue skill i had also enabled. Apparently there is a deploy button on the function which I had not clicked which does not seem to be in the documentation.

 Anyway thanks for publishing this, much easier that the haaska function to deploy and maintain, helped me migrate from a duckdns domain to my own domain very quickly.
