### ISSUE TITLE
TLS OWN CERT

### ISSUE THREAD

**Issue by NDNELSON** [fabsrc/home-assistant-alexa-proxy#4]
Hello , I have a question I am using this tea auth https://medium.com/@lukaszpinkosz/tls-client-authentication-for-your-home-assistant-e92452e26073

So where do I have to put my cert in amazon cloud to make it works?

Thanks a lot for the support

**Comment by fabsrc** [comment]
I think the simplest solution would be to store the cert and the key as files next to the lambda function file and load them into the Python SSL context using something like [load_cert_chain](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_cert_chain).
